
@startuml 菜谱制作引导页
(*) -right> "
{{
salt
{
<b>主要信息
菜谱名字 | "   "
运行时间 | "   "
调料步骤 | ^ 1 ^
状态步骤 | ^ 1 ^
[next] | [cancel]
}
}}
" as first

first -right> "
{{
salt
{
<b>调料信息
配料个数 | "   "
文字描述 | "   "
主料名称 | ^ 1 ^
文字描述 | ^ 1 ^
[next] | [cancel]
}
}}
" as second

second -right> "
{{
salt
{
<b>状态信息
运行状态 | "   "
锅盖状态 | "   "
搅动状态 | ^ 1 ^
火力功率 | ^ 1 ^
运行时间 | ^ 1 ^
运行温度 | ^ 1 ^
文字描述 | ^ 1 ^
[next] | [cancel]
}
}}
" as third

third -right>(*)

@enduml

@startuml bin文件融合引导页
(*) -right> "
{{
salt
{
<b>菜谱bin
文件地址
[选择所有文件]
[next] | [cancel]
}
}}
" as first

first -right> "
{{
salt
{
<b>图片8K
文件地址
[选择所有文件]
[next] | [cancel]
}
}}
" as second

second -right> "
{{
salt
{
<b>图片28K
文件地址
[选择所有文件]
[next] | [cancel]
}
}}
" as thrid

thrid -right> "
{{
salt
{
<b>图片60K
文件地址
[选择所有文件]
[next] | [cancel]
}
}}
" as fourth

fourth -right> "
{{
salt
{
<b>图片120K
文件地址
[选择所有文件]
[next] | [cancel]
}
}}
" as fiveth

fiveth -right> "
{{
salt
{
<b>字库bin
文件地址
[选择所有文件]
[next] | [cancel]
}
}}
" as sixth

sixth -right>(*)

@enduml