@startuml 软件使用时序图
title 灰尘灯条通信流程图
start
: 发送控制字节;
note right
|=开始 |= 功能 |= 数据长度 |= 数据 |= 校验和 |= 结束 |
| 0xF2 | 0xBB | 0x17 | 23字节 | 1字节 | 0x7F |
====
* 数据区分别存放10个蓝灯和10个红灯的亮度值，外加3个预留区
* 校验和：除了起始码与结束码外，
对其余的数据进行和校验（数据累加，取最低字节位）
end note

: 接受响应帧;
note right
|=开始 |= 功能 |= 数据长度 |= 数据 |= 校验和 |= 结束 |
| 0xF1 | 0xAA | 0x03 | 3字节 | 1字节 | 0x7E |
====
* 数据存放软件版本号
end note

if (响应帧正确?) then (设备码正确)
:继续发送控制字节;
else (响应帧错误或者没有返回信息)
:无法连接到灯条;
:灯条故障;
endif

stop
@enduml